# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # use `pre-commit autoupdate` to get the latest rev
    hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main'] # prevent local commits to main branch
    -   id: check-yaml # check for proper yaml formatting
    -   id: check-json # check for proper json formatting
#    -   id: pretty-format-json
#    -   id: end-of-file-fixer
#    -   id: trailing-whitespace
#-   repo: https://github.com/pre-commit/mirrors-csslint
#    rev: v1.0.5  # use `pre-commit autoupdate` to get the latest rev
#    hooks:
#    -   id: csslint
-   repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1  # use `pre-commit autoupdate` to get the latest rev
    hooks:
    -   id: curlylint
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
    -   id: prettier
        types: [json]
ci:
    autofix_prs: false
