# Inserts list of community members into ./README.md
name: Add contributors to README
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '10 2 * * 0' # At 02:10 on Sunday.

jobs:
  insert-contributors:
    runs-on: ubuntu-latest
    name: Add contributors
    steps:
      - name: Updates readme with contributors
        uses: akhilmhdh/contributors-readme-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore(README.md): updates contributors list'
