# Inserts list of community members into ./README.md
name: Add contributors to README
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '10 2 * * 0' # At 02:10 on Sunday.

jobs:
  insert-contributors:
    runs-on: ubuntu-latest
    name: Add contributors
    steps:
      - name: Updates readme with contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          image_size: 80
          readme_path: .github/README.md
          columns_per_row: 6
          commit_message: 'chore(README.md): updates contributors list'
